<?php
namespace Rindow\Database\Dao\Exception;

use Interop\Lenient\Dao\Exception\DeadlockLoserDataAccessException as DeadlockLoserDataAccessExceptionInterface;

class DeadlockLoserDataAccessException
extends PessimisticLockingFailureException
implements DeadlockLoserDataAccessExceptionInterface
{}
