<?php
namespace Rindow\Database\Dao\Exception;

use Interop\Lenient\Dao\Exception\InvalidDataAccessApiUsageException as InvalidDataAccessApiUsageExceptionInterface;

class InvalidDataAccessApiUsageException
extends NonTransientDataAccessException
implements InvalidDataAccessApiUsageExceptionInterface
{}
