<?php
namespace Rindow\Database\Dao\Exception;

use Interop\Lenient\Dao\Exception\TypeMismatchDataAccessException as TypeMismatchDataAccessExceptionInterface;

class TypeMismatchDataAccessException
extends InvalidDataAccessResourceUsageException
implements TypeMismatchDataAccessExceptionInterface
{}
