<?php
namespace Rindow\Database\Dao\Exception;

use Interop\Lenient\Dao\Exception\UncategorizedDataAccessException as UncategorizedDataAccessExceptionInterface;

class UncategorizedDataAccessException
extends NonTransientDataAccessException
implements UncategorizedDataAccessExceptionInterface
{}
